### ISSUE TITLE
Found a bug in the code in below code snippet 

### ISSUE THREAD

**Issue by skpandey91** [rohanKanojia/podsetoperatorinjava#4]
Comparing String with ==??
`public void onUpdate(Pod oldPod, Pod newPod) {
                if (oldPod.getMetadata().getResourceVersion() == newPod.getMetadata().getResourceVersion()) {
                    return;
                }
                handlePodObject(newPod);`

**Comment by rohanKanojia** [comment]
Thanks for noticing the bug. Let me fix this
